listen_port: 10088

introducer: fa23-cs425-4801.cs.illinois.edu

t_heartbeat: 1 #seconds
t_fail: 3 # seconds
t_cleanup: 5 # seconds

fan_out: 3 # determine choose how many neighbor to gossip

drop_rate: 0

default_suspicion: false
t_suspect: 3
t_confirm: 5

server_list:
  fa23-cs425-4801.cs.illinois.edu
  fa23-cs425-4802.cs.illinois.edu
  fa23-cs425-4803.cs.illinois.edu
  fa23-cs425-4804.cs.illinois.edu
  fa23-cs425-4805.cs.illinois.edu
  fa23-cs425-4806.cs.illinois.edu
  fa23-cs425-4807.cs.illinois.edu
  fa23-cs425-4808.cs.illinois.edu
  fa23-cs425-4809.cs.illinois.edu
  fa23-cs425-4810.cs.illinois.edu

